// import './css/plugins/animate.css'
import './css/plugins/swiper-bundle.min.css'
// import './css/plugins/jquery-ui.min.css'
import './css/plugins/countdownTimer.css'
import './css/plugins/slick.min.css'
import './css/plugins/nouislider.css'
import './css/plugins/bootstrap.css'